alias l 'ls -alrt'
alias v 'vim'
alias g 'gvim'
alias h 'history'
alias p 'pwd'
alias c 'clear'
alias j 'jobs'
alias bj 'bjobs'
alias bk 'bkill'
alias meld '/home/terwu01/bin/meld'

alias cd2 'cd ../..'
alias cd3 'cd ../../..'
alias cd4 'cd ../../../..'
alias cd5 'cd ../../../../..'
alias cd6 'cd ../../../../../..'
alias prj 'cd /project/pd/pj01269_teal/users/terwu01'
alias pd  'cd /project/pd/pj01269_teal/users/terwu01'
alias mi  'cd /project/pd/pj02774_mizar/users/terwu01'
#git shortcut
alias gst   'git status'
alias gck   'git checkout'
alias grst  'git restore'
alias gbr   'git branch'
alias gcf   'git config'
alias gfc   'git fetch'
alias gcm   'git commit'
alias grs   'git reset'
alias grb   'git rebase'
alias grv   'git revert'
alias gmg   'git merge'
alias gps   'git push'
alias gpl   'git pull'
alias gcp   'git cherry-pick'
alias glg   'git log --grapg'
alias gss   'git stash'
alias gad   'git add'
alias gdf   'git diff'
alias gmd   'git difftool'
alias gpr   'git pull --rebase'
alias grm   'git rm'
alias gcl   'git clean'
alias gcla  'grs HEAD --hard; gcl -d -f; gst'

