alias l 'ls -alrt'
alias v 'vim'
alias g 'gvim'
alias h 'history'
alias p 'pwd'
alias c 'clear'
alias j 'jobs'
alias bj 'bjobs'
alias bk 'bkill'
alias meld '/home/terwu01/bin/meld'

alias cd2 'cd ../..'
alias cd3 'cd ../../..'
alias cd4 'cd ../../../..'
alias cd5 'cd ../../../../..'
alias cd6 'cd ../../../../../..'
alias prj 'cd /project/pd/pj01269_teal/users/terwu01'
alias pd  'cd /project/pd/pj01269_teal/users/terwu01'
alias mi  'cd /project/pd/pj02774_mizar/users/terwu01'

#git shortcut
alias gst   'git st'
alias gck   'git ck'
alias grst  'git rst'
alias gbr   'git br'
alias gcf   'git config'
alias gfc   'git fc'
alias gcm   'git cm'
alias grs   'git rs'
alias grb   'git rb'
alias grv   'git rv'
alias gmg   'git mg'
alias gps   'git ps'
alias gpl   'git pl'
alias gcp   'git cp'
alias gss   'git stash'
alias gad   'git add'
alias gdf   'git diff'
alias gmd   'git difftool'
alias gcl   'git clean'
alias gpr   'git pr'
alias grm   'git rm'
alias gcla  'grs HEAD --hard; gcl -d -f; gst'
#fancy log
alias glg   'git lg'
alias gtr   'git tr'
alias glg1  'git lg1'
alias glg2  'git lg2'
#unstage file
alias gus   'git us'
#unstage and checkout file
alias grc   'git rc'
alias gsw   'git sw'
#checkout to HEAD~1
alias gud   'git ud'
#log last commmit
alias gls   'git ls'
#diff last commit from HEAD~1'
alias gdl   'git dl'
#show revision and arthur on last modified file
alias gbl   'git bl'
#show remote branch whicn contains the commit
alias gbc   'git bc'
#add all and commit -m
alias gacm  'git acm'
